changelog:
  categories:
    - title: Enhancements
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
    - title: Others
      labels:
        - "*"
