name: Testing

on: [ push ]

jobs:

  check-code-style:

    runs-on: ubuntu-22.04

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check Code Style
        run: composer phpcs-dry

  tests:
    name: "Tests"

    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"

    steps:
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: xdebug3

      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        run: composer install --no-progress

      - name: "Run test suite"
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
        
      - name: "Send coverage to codecov.io"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
